### ISSUE TITLE
Error: "Unable to link to archive"

### ISSUE THREAD

**Issue by Happy-Ferret** [esy-packages/esy-openssl#19]
Running ``esy`` from within the cloned project results in the following error message

```
error: unable to link to archive:https://github.com/openssl/openssl/archive/OpenSSL_1_1_1c.tar.gz#sha1:eb59b090bd757e30b676fb5e80c25ddb5a2f9511
  reading package metadata from link-dev:./package.json
  loading root package metadata
esy: exiting due to errors above
```

OS: Windows 10 (both Win32 and Windows Subsystem for Linux exhibit the same behavior)

**Comment by anmonteiro** [comment]
This is not a problem with this repo. Esy doesn't let you link to tarballs by design. This is why we've set up a little workaround in the CI to do this for us (https://github.com/esy-packages/esy-openssl/blob/esy/.ci/build.yaml#L16-L25)
